version: '3.8'

services:
  was:
    build: .
    depends_on:
      - mysql
    restart: unless-stopped
    expose:
      - 3000
  mysql:
    image: mysql:8.4.3
    expose:
      - 3306
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    restart: unless-stopped
